name: employee_directory
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^4.0.4
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  flutter_easyloading: ^3.0.3
  pretty_dio_logger: ^1.1.1
  splash: ^1.1.0
  cached_network_image: ^3.2.2
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.2
  lint: ^1.10.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

